services:
  timeclock-postgres:
    restart: always
    image: postgres:11
    expose:
      - "5432"
    ports:
      - 5432:5432
    env_file: .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data

  timeclock-server:
    build:
      dockerfile: ./Dockerfile
    env_file: .env
    user: "1000:1000"
    volumes:
      - .:/home/timeclock/timeclock/time_system:z,U
    ports:
      - 8000:8000
    expose:
      - "8000"
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=timeclock-postgres
      - ALLOW_CORS=1
      - DEV=1
    depends_on:
      - timeclock-postgres
    command: bash -c "/home/timeclock/timeclock/run.sh"

volumes:
  pgdata:
