# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-31 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clocker', '0003_auto_20160115_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='signatureDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
