# Generated by Django 3.2.25 on 2025-01-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clocker', '0004_timesheet_signaturedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(verbose_name='date employee was hired'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='username',
            field=models.TextField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(verbose_name='job description'),
        ),
        migrations.AlterField(
            model_name='job',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.TextField(verbose_name='job name'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='time_in',
            field=models.DateTimeField(verbose_name='clock in time'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='time_out',
            field=models.DateTimeField(blank=True, null=True, verbose_name='clock out time'),
        ),
        migrations.AlterField(
            model_name='shiftsummary',
            name='hours',
            field=models.IntegerField(verbose_name='total hours'),
        ),
        migrations.AlterField(
            model_name='shiftsummary',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='shiftsummary',
            name='note',
            field=models.TextField(blank=True, verbose_name='notes about job'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
